# =========================
# Project Identification
# =========================
sonar.projectKey=AparnaMounikau763_student_dashboard-22
sonar.organization=aparnamounikau763
sonar.projectName=student_dashboard-2
-Dsonar.qualitygate.wait=true
# =========================
# Source & Test Configuration
# =========================
sonar.sources=app
sonar.tests=tests

# =========================
# Python Settings
# =========================
sonar.python.version=3.10

# =========================
# Coverage Report
# =========================
sonar.python.coverage.reportPaths=coverage.xml

# =========================
# Exclusions
# =========================
sonar.exclusions=**/__pycache__/**,**/*.pyc

# =========================
# Encoding
# =========================
sonar.sourceEncoding=UTF-8
