sonar.projectKey=AparnaMounikau763_student_dashboard-22
sonar.organization=aparnamounikau763
sonar.projectName=student_dashboard-2

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.10

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8